id: P009268
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:49.341160
source_metadata:
  id: bdr:W1KG10746
  title: ས་ར་ཧ་པའི་རྡོ་རྗེའི་གསུང་རྣམས་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    e941f49e146543aca63a060cf5ca68f3:
      image_group_id: I1KG10748
      title: ''
      volume_number: 1
      total_pages: 1054
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
