id: P009268
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10746
  title: ས་ར་ཧ་པའི་རྡོ་རྗེའི་གསུང་རྣམས་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    e941f49e146543aca63a060cf5ca68f3:
      image_group_id: I1KG10748
      title: ''
      volume_number: 1
      total_pages: 1054
      base_file: v001.txt
